### ISSUE TITLE
Issues installing packages 

### ISSUE THREAD

**Issue by DDuran19** [daedalus-developers/hrs#10]
![image](https://github.com/daedalus-developers/hrs/assets/128191960/70ff9472-c9b6-43fc-a308-62ac7a7946b1)
The problem arises from the fact that not all libraries/ dependencies installed support react 18. As a proposed solution, I added an overrides fallback in package json.

```json
  "overrides": {
    "react": "^18"
  }
```

**Comment by directormac** [comment]
The repo uses `pnpm`.
